# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
r:
  - oldrel
  - release
  - devel
sudo: required
cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev

r_github_packages:
  - ropensci/USAboundaries
  - ropensci/USAboundariesData

notifications:
  email:
    on_success: never
    on_failure: always
