# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libgdal-dev
      - libgeos-dev
      - libproj-dev
      - libudunits2-dev
      - liblwgeom-dev

notifications:
  email:
    on_success: never
    on_failure: always
